BettingWebApp/Models/MatchOdd.cs
using System.ComponentModel.DataAnnotations;

namespace BettingWebApp.Models
{
    public class MatchOdd
    {
        [Required]
        public int ID { get; set; }
        [Required]
        public int MatchID { get; set; } //Entity Framework interprets a property as a foreign key property if it's named<navigation property name><primary key property name>
        //public virtual Match Match { get; set; }

        [StringLength(500, ErrorMessage = "The value declared for Specifier is too long")]
        [Required(ErrorMessage = "Specifier is required")]
        public string Specifier { get; set; }

        //[Range(0, 999.99)] //no idea which should be the range
        [Required(ErrorMessage = "Odd is required")]
        public double Odd { get; set; }

        public MatchOdd()
        {

        }
    }
}

BettingWebApp/ViewModels/MatchOddViewModel.cs
using BettingWebApp.Models;
using System.Collections.Generic;

namespace BettingWebApp.ViewModels
{
    //This class eventually was not used, but it might be used
    //for updates in the near future, thus, I will not delete it
    public class MatchOddViewModel
    {
        public Match Match { get; set; }
        public IEnumerable<MatchOdd> MatchOdds { get; set; }
        public MatchOdd MatchOdd { get; set; }

    }
}

BettingWebApp/Controllers/MatchOddsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BettingWebApp.Data;
using BettingWebApp.Models;

namespace BettingWebApp.Controllers
{
    public class MatchOddsController : Controller
    {
        private readonly ApplicationDbContext _context;


        public MatchOddsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: MatchOdds
        public async Task<IActionResult> Index(int? matchId)
        {

            ViewBag.matchID = matchId;
            return View(await _context.MatchOdd.Where(i => i.MatchID == matchId).ToListAsync());
        }

        // GET: MatchOdds/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var matchOdd = await _context.MatchOdd
                .FirstOrDefaultAsync(m => m.ID == id);
            if (matchOdd == null)
            {
                return NotFound();
            }

            return View(matchOdd);
        }

        // GET: MatchOdds/Create
        public IActionResult Create(int? matchId)
        {
            ViewData["MatchID"] = matchId;
            return View();
        }


        // POST: MatchOdds/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,MatchID,Specifier,Odd")] MatchOdd matchOdd)
        {
            if (ModelState.IsValid)
            {

                _context.Add(matchOdd);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                return RedirectToAction("Select", "Matches", new { id = matchOdd.MatchID });
            }
            return View(matchOdd);
        }

        // GET: MatchOdds/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var matchOdd = await _context.MatchOdd.FindAsync(id);
            if (matchOdd == null)
            {
                return NotFound();
            }
            return View(matchOdd);
        }

        // POST: MatchOdds/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,MatchID,Specifier,Odd")] MatchOdd matchOdd)
        {
            if (id != matchOdd.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(matchOdd);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MatchOddExists(matchOdd.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                //return RedirectToAction(nameof(Index));
                return RedirectToAction("Select", "Matches", new { id = matchOdd.MatchID });
            }
            return View(matchOdd);
        }

        // GET: MatchOdds/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var matchOdd = await _context.MatchOdd
                .FirstOrDefaultAsync(m => m.ID == id);
            if (matchOdd == null)
            {
                return NotFound();
            }

            return View(matchOdd);
        }

        // POST: MatchOdds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var matchOdd = await _context.MatchOdd.FindAsync(id);
            _context.MatchOdd.Remove(matchOdd);
            await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index));
            return RedirectToAction("Select", "Matches", new { id = matchOdd.MatchID });
        }

        private bool MatchOddExists(int id)
        {
            return _context.MatchOdd.Any(e => e.ID == id);
        }
    }
}

BettingWebApp/Views/MatchOdds/Create.cshtml
@*@model BettingWebApp.Models.MatchOdd*@
@model BettingWebApp.Models.MatchOdd



@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Match Odd</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MatchID" />
            @* <div class="form-group">
            <label asp-for="MatchID" class="control-label"></label>
            <input asp-for="MatchID" class="form-control">
            <span asp-validation-for="MatchID" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Specifier" class="control-label"></label>
                <input asp-for="Specifier" class="form-control" />
                <span asp-validation-for="Specifier" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Odd" class="control-label"></label>
                <input asp-for="Odd" class="form-control" />
                <span asp-validation-for="Odd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Matches" asp-action="Select" asp-route-id="@ViewData["MatchID"]">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

BettingWebApp/Views/MatchOdds/Delete.cshtml
@model BettingWebApp.Models.MatchOdd

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Match Odd</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Specifier)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Specifier)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Odd)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Odd)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="Matches" asp-action="Select" asp-route-id="@Model.MatchID">Back to List</a>
    </form>
</div>

BettingWebApp/Views/MatchOdds/Details.cshtml
@model BettingWebApp.Models.MatchOdd

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Match Odd</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Specifier)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Specifier)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Odd)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Odd)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="MatchOdds" asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-controller="Matches" asp-action="Select" asp-route-id="@Model.MatchID">Back to List</a>
</div>

BettingWebApp/Views/MatchOdds/Edit.cshtml
@model BettingWebApp.Models.MatchOdd

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Match Odd</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <input type="hidden" asp-for="MatchID" />
            @*<div class="form-group">
            <label asp-for="MatchID" class="control-label"></label>
            <input asp-for="MatchID" class="form-control" value=@ViewData["matchID"]>
            <span asp-validation-for="MatchID" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Specifier" class="control-label"></label>
                <input asp-for="Specifier" class="form-control" />
                <span asp-validation-for="Specifier" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Odd" class="control-label"></label>
                <input asp-for="Odd" class="form-control" />
                <span asp-validation-for="Odd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Matches" asp-action="Select" asp-route-id="@Model.MatchID">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

BettingWebApp/Views/MatchOdds/Index.cshtml
@model IEnumerable<BettingWebApp.Models.MatchOdd>

@{
    ViewData["Title"] = "Index";
}



<h1>Match Odds</h1>

<div>
    <a asp-action="Index">Back to List</a>
</div>


<p>
    @Html.ActionLink("Create New Odd", "Create",  "MatchOdds", routeValues: new {matchId = ViewData["MatchID"]})

</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Specifier)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Odd)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Specifier)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Odd)
                </td>

                <td>
                    <a asp-controller="MatchOdds" asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-controller="MatchOdds" asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-controller="MatchOdds" asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>